### PR TITLE
Major cleanup

### PR DESCRIPTION
**Pull request by pinn3**
This pull request consists of the following:
- [x] Adds [standardJS](https://github.com/feross/standard), as well as [ECMAScript 2015](https://babeljs.io/docs/learn-es2015/) syntax
- [x] Restructures the repository with distinct source and build directories
- [x] **Should** still be completely backwards compatible thanks to babel

### CODE REVIEW

**Comment by mcwhittemore** [comment]
@pinn3 is gist-db something you want to actively work on? If so, I can transfer this project to you. I haven't used it in a really long time.

**Comment by pinn3** [comment]
Yeah sure! I wrote to you on gitter regarding this.

**Comment by mcwhittemore** [comment]
Feel free to merge @pinn3. Once you can delete you're fork I can transfer this to you.

**Comment by pinn3** [comment]
@mcwhittemore All done!

**Pull request merged**
